[programs.localnet]
xapes_staking = "Bbj49DaVQmAFFYceo2wtpyhkQkbtGtsioB348xHAZMhx"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
