[programs.devnet]
punky_staking = "Ej8CaD3gWKSQAqZeGsV9UAiVGeu56wN5SP5vNgeQ3dN3"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/opt/Apyra/keypair/devnet-ApyraDev.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
